// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Test schema representing client-configured policies.
// It is used by the `proto_to_predicate` tool to translate Protobuf policies
// into CEL predicates.
edition = "2023";

package cel.cpp.tools;

import "google/protobuf/descriptor.proto";

option cc_enable_arenas = true;

extend google.protobuf.FieldOptions {
  string match_path = 51074;
}

// Represents the targeted client agent.
message Agent {
  string name = 1 [json_name = "id"];
  string location = 2 [(match_path) = "custom.agent.location"];
}

// Specifies additional metadata tool annotations.
message ToolAnnotations {
  bool read_only_hint = 1;
}

// Represents a mapped nested message entry value inside map fields.
message Members {
  repeated string principals = 1;

  repeated string regions = 2;

  bool all_users = 3;

  bool all_authenticated_users = 4;

  string leader = 5 [(match_path) = "custom.member.leader"];

  repeated string leaders = 6 [(match_path) = "custom.member.leaders"];
}

// Represents a metadata tool block.
message Tool {
  // The name of the tool.
  string name = 1;

  // Additional metadata annotations for the tool.
  ToolAnnotations annotations = 2;

  // A string-to-string map, transpiled as conjoined existence and equality
  // checks.
  map<string, string> labels = 3;

  // A map with string keys representing roles and Member instances as values.
  map<string, Members> role_members = 4;

  // A map with string keys representing roles and Member instances as values,
  // annotated with a match_path.
  map<string, Members> annotated_role_members = 5
      [(match_path) = "custom.role_members"];

  // A string-to-string map, annotated with a match_path.
  map<string, string> annotated_labels = 6 [(match_path) = "custom.labels"];

  // A non-repeated message field, annotated with a match_path.
  ToolAnnotations annotated_annotations = 7
      [(match_path) = "custom.tool_annotations"];

  // A repeated message field, annotated with a match_path.
  repeated Agent backup_agents = 8 [(match_path) = "custom.backup_agents"];
}

// Represents a policy mapping destination block.
message Target {
  oneof kind {
    Agent agent = 1;
    Tool tool = 2;
    string ip = 3 [(match_path) = "custom.ip"];
  }
}

// Represents the top-level policy containing multiple alternate destination
// rules.
message Policy {
  repeated Target destinations = 1;
}
